---
- name: Configure web server for .NET core application
  hosts: adv
  become: true
  vars:
    adv_domain: dev.uttamgolds.in
  tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true

    - name: Install .NET runtime
      ansible.builtin.apt:
        name:
          - dotnet-runtime-8.0
          - aspnetcore-runtime-8.0
        state: present

    - name: Install ASP.NET Core runtime
      ansible.builtin.apt:
        name: aspnetcore-runtime-8.0
        state: present

    - name: Install Nginx
      ansible.builtin.apt:
        name: nginx
        state: present

    - name: Create application user
      ansible.builtin.user:
        name: www-data
        group: www-data

    - name: Create app directory
      ansible.builtin.file:
        path: /var/www/advapp
        state: directory

    - name: Copy application binaries
      ansible.builtin.copy:
        src: /Users/tapra/repos/tsamanta/terraform-poc/artifacts/
        dest: /var/www/advapp
        owner: www-data
        group: www-data
        mode: 0644

    - ansible.builtin.template:
        src: nginx-server.j2
        dest: /etc/nginx/sites-available/default
    - name: Retart nginx to reload server configuration
      ansible.builtin.command: nginx -s reload

    - name: Copy systemd service file
      ansible.builtin.copy:
        src: kestrel-advapp.service
        dest: /etc/systemd/system/kestrel-advapp.service

    - name: Start systemtl service
      ansible.builtin.systemd:
        state: started
        name: kestrel-advapp
