name: Adventure works DevOps automation
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
env:
  SOLUTION_NAME: src/advapp/advapp.sln
  AZURE_WEBAPP_PACKAGE_PATH: artifacts
  AZURE_WEBAPP_RUNTIME: "DOTNETCORE:8.0"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y dotnet-sdk-8.0
          cd src/advapp
      - name: Restore dependencies
        run: dotnet restore */**/*.sln
      - name: Build
        run: dotnet build */**/*.sln --configuration Release --no-restore
      - name: Test
        run: dotnet test */**/*.Tests.csproj --no-restore --no-build --verbosity normal --logger:"trx;LogFilePrefix=testResults"
      - name: Publish
        run: dotnet publish */**/*.Web.csproj -c Release -o ./artifacts --no-build /p:DebugType=Non/p:DebugType=None /p:DebugSymbols=false
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: artifacts
          path: artifacts
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: artifacts
